family = ['Mohsen','Batool']
print(f"At first my family starts with {family}.")
family.append('Yasaman')
print(f"After two years my family became {family}.")
family.append('Mahdi')
print(f"After ten years my family became {family}.")
family.pop(2)
family.insert(2, 'Hoshang')
print(f"After eight years my family became {family}.")
del family[2]
family.insert(2, 'Atta')
print(f"After two years my family became {family}.")
family.append('Setareh')
print(f"After six years my family became {family}.")
family.append('Parmis')
print(f"I wish my family one day becomes {family}.")
family.remove('Parmis')
print(f"original list of my family now: {family}")
print(f"sorted list of my family: {sorted(family)}")
print(f"original list of my family: {family}")
print(f"sorted reverse list of my family: {sorted(family , reverse=True)}")
print(f"original list of my family: {family}")
family.reverse()
print(f"original list of my family after reversed: {family}")
family.reverse()
print(f"original list of my family after reversed again: {family}") 
family.sort()
print(f"original list of my family after sorted: {family}")
family.sort(reverse=True)
print(f"original list of my family after reversed sorted: {family}")