worlds_places = ['Takht-e Jamshīd','Ancient Egypt','Vatican City','New York Art Museum']
print(f"original list: {worlds_places}")
print(f"sorted list: {sorted(worlds_places)}")
print(f"original list: {worlds_places}")
print(f"sorted reverse list: {sorted(worlds_places , reverse=True)}")
print(f"original list: {worlds_places}")
worlds_places.reverse()
print(f"original list after reversed: {worlds_places}")
worlds_places.reverse()
print(f"original list after reversed again: {worlds_places}")
worlds_places.sort()
print(f"original list after sorted: {worlds_places}")
worlds_places.sort(reverse=True)
print(f"original list after reversed sorted: {worlds_places}")